name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout rgbds
        uses: actions/checkout@master
        with:
          path: rgbds
          ref: v1.0.0
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo apt-get install -yq libpng-dev
          sudo make install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      - name: Make
        run: |
          make -j$(nproc)

      - name: Upload ROM artifact
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: pokecrystal-cat
          path: "*.gbc"

      - name: Upload ROM to release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v1
        with:
          files: "*.gbc"
